import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Soccer Rumor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      {/* flex: 정렬 */}
      {/* flex-col: 정렬의 방향을 위에서 아래로 */}
      <body className="flex flex-col">
        <header className="bg-yellow-300 top-0">Header</header>
        {/* grow: 부족한 공간만큼 늘려준다*/}
        <main className="bg-blue-200 grow w-full max-w-screen-xl mx-auto">
          {children}
        </main>

        <footer className="bottom-0 bg-green-200">Footer</footer>
      </body>
    </html>
  );
}
